import { ObjectId } from "mongodb";

export interface Admin {
  _id?: ObjectId;       // generated by MongoDB
  name: string;         // admin name
  email: string;        // admin email
  passwordHash: string; // hashed password
  role: "admin";        // role for authorization
  createdAt: Date;      // timestamp
}
